### ISSUE TITLE
Latest commit broke the repo sync process

### ISSUE THREAD

**Issue by Umeaboy** [MyOLDREPOSITORY/android_vendor_samsung_zero-common_old#1]
I was resyncing today and your latest commit to update blobs to Nougat broke something.
Can you either revert it or fix it?

**Comment by sailinggalaxians** [comment]
It's still not syncing OK:

error: vendor/samsung/zero-common/: Giugiu19/android_vendor_samsung_zero-common checkout 079e4e58ecc41e4998ad416c7012b9b47b0f926d

**Comment by Umeaboy** [comment]
Can you check what you made wrong and push changes to fix it or not?
